### ISSUE TITLE
Enable mlir-aie to aiesimulator flow

### ISSUE THREAD

**Issue by ywshao** [Xilinx/mlir-aie#100]
There is an aiecompiler to aiesimulator flow in Vitis. I would like to know if there is a way to replace aiecompiler with mlir-aie, i.e., having a mlir-aie to aiesimulator flow.

**Comment by stephenneuendorffer** [comment]
There's not a direct way to do this today.  Conceptually, the ADF dialect would be the best place to integrate with the aiecompiler tools.  However, this level of abstraction doesn't yet map into the AIE dialect.  Conversely, aiesimulator doesn't readily exist as a separate component that the AIE dialect could interface to.

**Comment by jackl-xilinx** [comment]
We are looking into enabling some level of integration from mlir-aie to aiesimulator and hope to have an update in the next few weeks.

**Comment by jackl-xilinx** [comment]
This should now be enabled. Please see tutorial-2b for more details
