### ISSUE TITLE
Windows CI requires OpenSSL for bootgen

### ISSUE THREAD

**Issue by stephenneuendorffer** [Xilinx/mlir-aie#1016]
Bootgen is currently not built on windows.  it requires:

1. Download and install "Win64 OpenSSL v1.1.1b", from http://slproweb.com/products/Win32OpenSSL.html.

**Comment by makslevental** [comment]
![Screenshot from 2024-02-18 20-10-48](https://github.com/Xilinx/mlir-aie/assets/5657668/5f525c12-6bd0-42d0-a943-eb6de39dcbac)

Disabled until I get around to updating the container with ssl.
