### ISSUE TITLE
`appendWriteBdShimTile` (in `AIETargetIPU`) sets the wrong words/fields

### ISSUE THREAD

**Issue by makslevental** [Xilinx/mlir-aie#1028]
https://github.com/Xilinx/mlir-aie/blob/cb232a43383ef3b8efd8b408545c9b74885578ad/lib/Targets/AIETargetIPU.cpp#L100-L104

is wrong; see https://gitenterprise.xilinx.com/IPU/dpufw/blob/dev/include/RunInstOpt.h#L675 which reads `AddrHigh = (iptr[4] & 0x0000FFFF)` from that word in the instruction sequence. It hasn't come up because no one has set any of "En Packet , OoO BD ID , Packet ID , Packet Type" to anything before (so they're all 0).

**Comment by fifield** [comment]
The c++ code is setting the upper bits, which are the packet fields, and the code in the link is reading the lower bits which is part of the base address. I don't see the conflict, but I've only started my first cup of coffee.

We have tested packet routing from the shim dma and it works. We probably need to resurrect a few tests from the pre-open source repo.

**Comment by makslevental** [comment]
> The c++ code is setting the upper bits, which are the packet fields, and the code in the link is reading the lower bits which is part of the base address. I don't see the conflict, but I've only started my first cup of coffee.
> 
> We have tested packet routing from the shim dma and it works. We probably need to resurrect a few tests from the pre-open source repo.

Yea I just did a double take (issue posted at 2am :sweat_smile:) and noticed everything is shifted at least 16 (and the fw masks out the upper 16 bits and only reads `AddrLow` from the lower 16). Sorry for the false alarm.
