### ISSUE TITLE
Error during create-flows/broadcast.mlir (Ubuntu 18.04 and gcc 7.5.0)

### ISSUE THREAD

**Issue by AndraBisca** [Xilinx/mlir-aie#13]
Error is:
error: CHECK: expected string not found in input
// CHECK: AIE.flow(%[[T20]], DMA : 0, %[[T82]], DMA : 0)
          ^
<stdin>:297:37: note: scanning from here
 AIE.flow(%6, DMA : 0, %12, DMA : 0)
                                    ^
<stdin>:297:37: note: with "T20" equal to "6"
 AIE.flow(%6, DMA : 0, %12, DMA : 0)
                                    ^
<stdin>:297:37: note: with "T82" equal to "16"
 AIE.flow(%6, DMA : 0, %12, DMA : 0)
                                    ^
<stdin>:298:2: note: possible intended match here
 AIE.flow(%6, DMA : 0, %9, DMA : 0)

**Comment by erwei-xilinx** [comment]
I'm unable to reproduce the error. I wonder if this issue still occurs in the most recent hash?
