### ISSUE TITLE
ASPLOS Tutorial "Linux Setup and Build Instructions" File not found for add_one_objFifo

### ISSUE THREAD

**Issue by ypapadop-amd** [Xilinx/mlir-aie#1436]
In https://github.com/Xilinx/mlir-aie/blob/asplos/docs/buildHostLin.md#build-a-design the link `add_one_objFifo` points to https://github.com/Xilinx/mlir-aie/blob/asplos/reference_designs/ipu-xrt/add_one_objFifo which does not exist.

**Comment by fifield** [comment]
> In https://github.com/Xilinx/mlir-aie/blob/asplos/docs/buildHostLin.md#build-a-design the link `add_one_objFifo` points to https://github.com/Xilinx/mlir-aie/blob/asplos/reference_designs/ipu-xrt/add_one_objFifo which does not exist.

This was "fixed" in main, then broken again when vector_add was removed.
