### ISSUE TITLE
Linking errors in chess_compiler_tests (Ubuntu 18.04 and gcc 7.5.0)

### ISSUE THREAD

**Issue by AndraBisca** [Xilinx/mlir-aie#15]
01_precompiled_core_function:
Error: Undefined symbol "func"
... Symbol is referenced in file   : core_1_3.chesslinked.o (core_1_3.chesslinked.o)
... Symbol is referenced in : _main @ offset 80
Error in "core_1_3.elf.map": Linking ended with errors, check the map file for an overview of already mapped symbols.
xchesscc Failed

03_cascade:
Error: Undefined symbol "do_mul"
... Symbol is referenced in file   : core_1_3.chesslinked.o (core_1_3.chesslinked.o)
... Symbol is referenced in : _main @ offset 0
Error in "core_1_3.elf.map": Linking ended with errors, check the map file for an overview of already mapped symbols.
xchesscc Failed

05_shim_dma_core_function:
Error: Undefined symbol "func"
... Symbol is referenced in file   : core_7_3.chesslinked.o (core_7_3.chesslinked.o)
... Symbol is referenced in : _main @ offset 240
Error: Undefined symbol "func"
... Symbol is referenced in file   : core_7_3.chesslinked.o (core_7_3.chesslinked.o)
... Symbol is referenced in : _main @ offset 80
Error in "core_7_3.elf.map": Linking ended with errors, check the map file for an overview of already mapped symbols.
xchesscc Failed

07_shim_dma_with_core:
Error: Undefined symbol "func"
... Symbol is referenced in file   : core_7_3.chesslinked.o (core_7_3.chesslinked.o)
... Symbol is referenced in : core73 @ offset 1360
Error: Undefined symbol "func"
... Symbol is referenced in file   : core_7_3.chesslinked.o (core_7_3.chesslinked.o)
... Symbol is referenced in : core73 @ offset 1184
Error: Undefined symbol "func"
... Symbol is referenced in file   : core_7_3.chesslinked.o (core_7_3.chesslinked.o)
... Symbol is referenced in : core73 @ offset 1008
Error: Undefined symbol "func"
... Symbol is referenced in file   : core_7_3.chesslinked.o (core_7_3.chesslinked.o)
... Symbol is referenced in : core73 @ offset 832
Error: Undefined symbol "func"
... Symbol is referenced in file   : core_7_3.chesslinked.o (core_7_3.chesslinked.o)
... Symbol is referenced in : core73 @ offset 624
Error: Undefined symbol "func"
... Symbol is referenced in file   : core_7_3.chesslinked.o (core_7_3.chesslinked.o)
... Symbol is referenced in : core73 @ offset 448
Error: Undefined symbol "func"
... Symbol is referenced in file   : core_7_3.chesslinked.o (core_7_3.chesslinked.o)
... Symbol is referenced in : core73 @ offset 272
Error: Undefined symbol "func"
... Symbol is referenced in file   : core_7_3.chesslinked.o (core_7_3.chesslinked.o)
... Symbol is referenced in : core73 @ offset 96
Error in "core_7_3.elf.map": Linking ended with errors, check the map file for an overview of already mapped symbols.
xchesscc Failed

**Comment by stephenneuendorffer** [comment]
The problem here is that we need to implement the link_with= capability with chess's version of a linker script.
