### ISSUE TITLE
MLIR::loopUnrollByFactor fails for small loops

### ISSUE THREAD

**Issue by AndraBisca** [Xilinx/mlir-aie#1556]
After #1545 designs with loops that have less iterations than the unroll factor fail silently. 

It was caught by one of @eddierichter-amd designs.

The example [here](https://github.com/Xilinx/mlir-aie/blob/unroll-bug/test/objectFifo-stateful-transform/loop_test_small.mlir) shows this error and expected output. The loop has 4 iterations and the unroll factor is 6.

@jtuyls

**Comment by makslevental** [comment]
You can use this to compute the trip count of an `scf.for` with static bounds and step: https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/Dialect/Utils/StaticValueUtils.h#L175.

**Comment by makslevental** [comment]
```cpp
          if (!forLoop.getSingleLowerBound() ||
              !forLoop.getSingleUpperBound() || !forLoop.getSingleStep() ||
              constantTripCount(*forLoop.getSingleLowerBound(),
                                *forLoop.getSingleUpperBound(),
                                *forLoop.getSingleStep())
                      .value_or(0) >= unrollFactor)
            forLoop.emitOpError()
                << "could not be unrolled because tripcount < unrollFactor: "
                << unrollFactor << "\n"
```
