### ISSUE TITLE
About vck190 boot from sd card?

### ISSUE THREAD

**Issue by HadXu** [Xilinx/mlir-aie#167]
I build aie_platform successfully. And I copy mlir-aie/platforms/vck190_bare_prod/aie_platform/sd_dir files to sd card of fat32 format. But  do not boot successfully. Do I left something or ?

![image](https://user-images.githubusercontent.com/13307469/190963780-63e2dc73-8427-479f-987b-596501902806.png)

**Comment by jgmelber** [comment]
Did you copy the files to the SD card or flash the .img file onto the SD card? The proper procedure is to flash the .img file

**Comment by HadXu** [comment]
I copy mlir-aie/platforms/vck190_bare_prod/aie_platform/sd_dir files to sd card of fat32 format, But I failed. However, I flash the sd_card.img file to sd card, and it boot successfully. Thanks. I think the full documentation should be detailed.

**Comment by HadXu** [comment]
I copy mlir-aie/platforms/vck190_bare_prod/aie_platform/sd_dir files to sd card of fat32 format, But I failed. However, I flash the sd_card.img file to sd card, and it boot successfully. Thanks. I think the full documentation should be detailed.
