### ISSUE TITLE
Explicitly add control packet / task complete token routing to designs targeting NPU

### ISSUE THREAD

**Issue by jgmelber** [Xilinx/mlir-aie#1702]
This [code](https://github.com/Xilinx/mlir-aie/blob/d5b8f22dc2b2d8b80cbfffccda3146b64102b139/lib/Targets/AIETargetCDODirect.cpp#L611-L618) implicitly inserts routing for control packets for task complete tokens for NPU targets. This should be added explicitly to designs, including appropriate routing for task complete tokens from non-shim tiles for example in #1691. 

@fifield @erwei-xilinx @pvasireddy-amd @Yu-Zhewen

**Comment by erwei-xilinx** [comment]
WiP: https://github.com/erwei-xilinx/mlir-aie/tree/column_control_overlay

**Comment by erwei-xilinx** [comment]
PR ready for review: https://github.com/Xilinx/mlir-aie/pull/1705

**Comment by erwei-xilinx** [comment]
Close as PR has landed.
