### ISSUE TITLE
Refine Python API

### ISSUE THREAD

**Issue by hunhoffe** [Xilinx/mlir-aie#1806]
This issue is a method of tracking/deconflicting efforts to change the Python API. If anyone has any PRs to change the Python API please let me know and we can record them here! We can also use this issue to record ideas/brainstorming before a PR is created.

### Completed ###
- https://github.com/Xilinx/mlir-aie/pull/1786
- https://github.com/Xilinx/mlir-aie/pull/1785
- https://github.com/Xilinx/mlir-aie/pull/1791
- https://github.com/Xilinx/mlir-aie/pull/1800
- https://github.com/Xilinx/mlir-aie/pull/1817
- https://github.com/Xilinx/mlir-aie/pull/1824
- https://github.com/Xilinx/mlir-aie/pull/1818 
- https://github.com/Xilinx/mlir-aie/pull/1829
- https://github.com/Xilinx/mlir-aie/pull/1828 
- https://github.com/Xilinx/mlir-aie/pull/1870
- (Contains some python cleanup code, but some other stuff too) https://github.com/Xilinx/mlir-aie/pull/1919
- https://github.com/Xilinx/mlir-aie/pull/1732
- https://github.com/Xilinx/mlir-aie/pull/1941
- https://github.com/Xilinx/mlir-aie/issues/1923

**Comment by fifield** [comment]
> * Clean up WriteRTP/Buffer APIs e.g., code like here:

It's not clear to me that we still need the RTP ops, given that `npu.write32` and `npu.blockwrite` offer essentially the same functionality. What's the plan for RTP ops?

**Comment by hunhoffe** [comment]
@fifield I didn't have anything major planned, I'm just trying to get rid of all the Python operations that expect symbol names instead of python objects, so I was thinking about changing
```python
NpuWriteRTPOp("rtpComputeTile2", index=0, value=50) 
```
To either
```python
rtpComputeTile2.rtpWrite(index=0, value=50)
```
or (not sure if this is possible to infer the right type of write, so maybe not)
```python
rtpComputeTile2[0] = 50
```

Currently, NpuWriteRTPOp is used in the following programming examples:
* ml/resnet/layers_conv2_x
* ml/conv2d_fused_relu
* ml/bottleneck
* ml/conv2d
* vision/color_threshold/aie2_colorThreshold.py

I'm not sure what the differences between `NpuWriteRTPOp` and `npu.write32`/`npu.blockwrite` are, but alternatively I could try to port those examples to use `npu.write32`/`npu.blockwrite` instead?

**Comment by hunhoffe** [comment]
To record decisions make offline: RTP ops will probably be used with some additional synchronization method in the future, so it's worth it to clean up the Python interface

**Comment by hunhoffe** [comment]
Immediately planned work has been completed
