### ISSUE TITLE
Is mlir-aie supported on Kria Boards specifically KV260 ?

### ISSUE THREAD

**Issue by gautam1858** [Xilinx/mlir-aie#1815]
Is mlir-aie supported on Kria Boards specifically KV260 ?

**Comment by fifield** [comment]
> Is mlir-aie supported on Kria Boards specifically KV260 ?

No, the Kira boards are not supported by mlir-aie. My understanding is that the Kira boards is based on the Zynq Ultrascale+ MPSoC which are FPGA devices. The mlir-aie project is focused on AI Engine enabled devices such as Versal AI and Ryzen AI.
