### ISSUE TITLE
Build issue in tutorial2-a

### ISSUE THREAD

**Issue by kimm240** [Xilinx/mlir-aie#1903]
When I try to build tutorial2-a, this error occurs.

![image](https://github.com/user-attachments/assets/370e90df-68d8-43a8-90ce-81df0814a9cc)

When I check directory mlir-aie/install/runtime_lib, There is just 86_64, and aarch64 is not in there.

What should i do to fix that?

**Comment by kimm240** [comment]
I follow step: Building on X86 for mlir-aie development in https://github.com/Xilinx/mlir-aie/blob/main/docs/Building.md .

**Comment by jgmelber** [comment]
Hi! Which device are you building for?

**Comment by kimm240** [comment]
I build it for a Ryzen AI system,
so when I build it,
I use this code
'
source <Vitis Install Path>/settings64.sh
./utils/build-mlir-aie.sh <llvm dir>/<build dir>
'.

And my situation is like this:::
I'm just beginner in mlir so there is no target device,
but just want to check how mlir is compiled so I want to see code is running on x86(cpu).

**Comment by jgmelber** [comment]
You shouldn't need aarch64, for this example you should target x86 for the host code and library compilation. Can you remove the aarch64 target from the cmake build command?

**Comment by jgmelber** [comment]
The tutorials do not support Ryzen AI, those target embedded AIE devices.
