### ISSUE TITLE
Missing info on the README on how to activate IRON Env

### ISSUE THREAD

**Issue by TizianoDeMatteis** [Xilinx/mlir-aie#1918]
Hello,
I noticed that in your README, the "Build an IRON Design for AIEs in the AMD Ryzen™ AI NPU" section assumes you are in the `ironenv` created by the installation script in the previous step.

I think is more correct to mention that you have to be in the environment to compile/run something (or you have to do something like `source ironenv/bin/activate`.

**Comment by AndraBisca** [comment]
Good point, thank you for taking the time to file an issue!
