### ISSUE TITLE
Link to tutorial doesn't work

### ISSUE THREAD

**Issue by AJ-RR** [Xilinx/mlir-aie#1928]
Link to tutorial in the readme for programming guide section 2 doesn't work.

"NOTE: For more in-depth, low-level material on Object FIFO programming in MLIR, please see the MLIR-AIE [tutorials](https://github.com/Xilinx/mlir-aie/blob/main/programming_guide/mlir_tutorials)"

**Comment by AndraBisca** [comment]
Thank you for pointing this out!
