### ISSUE TITLE
Could not run Programming Examples on HX 370

### ISSUE THREAD

**Issue by ngdymx** [Xilinx/mlir-aie#1946]
I just bought a beelink SER9 mini pc with HX370 CPU. I have successfully installed the xrt and mlir-aie on it. Here is the output of the `xrt-smi examine` command:
![image](https://github.com/user-attachments/assets/cacaafc4-0b76-49d7-be91-e2cf360fb766)

However, when I tried to run the programming examples, I found only the examples with no kernel (passthrough_dmas) could run while all examples with kernels (passthrough_kernel) could not run with the error of `std::runtime_error`. Also, I found in the AIE Dialect, the supported devices are `npu1, npu1_<1, 2, 3, 4>col, and npu2`. I tried to used `npu2` but it still doesn't work. May I ask how to use all AIE cores in the HX 370? Thanks a lot!

**Comment by jgmelber** [comment]
#1952

**Comment by ngdymx** [comment]
Thanks, I will try it.

**Comment by jgmelber** [comment]
This enabled some examples, more to follow soon. Thanks for trying!

**Comment by ngdymx** [comment]
Hi @jgmelber,

I reinstall the environment,  and run the ```xrt-smi examine``` can get the ```RyzenAI-npu4```.

![image](https://github.com/user-attachments/assets/2551af3b-cd9b-4388-a42e-47354b75623e)

Then I try to run the example under ```programming_examples/basic```. But, I get an error shown in the following figure. What should I do now? Could you help me with it? Thanks!

![image](https://github.com/user-attachments/assets/3e610169-e4a5-4678-b3fa-b3730a69f24c)

**Comment by jgmelber** [comment]
Only some of the programming examples are enabled at this time. Which are you trying? 

Can you also share the version of xchesscc you have installed? You will need the version from the early access release of the Ryzen AI Software 1.3: Vitis AIE Essentials. 

It looks like you're using the Peano compiler in this example, the version of AIE in Strix laptops is not currently supported with that single core compiler.

**Comment by ngdymx** [comment]
Hi @jgmelber,

Thanks!

I was running the ```programming_examples/basic/passthrough_dmas```, changing the ```dev``` under ```passthrough_dmas_alt.py``` to ```npu2``` and the corresponding ```Makefile```. 

The version of xchesscc is ```U-2022.12#3eec2545bc#230622```.

![image](https://github.com/user-attachments/assets/44d4a3b7-69e7-4b26-b97d-9971f82ad773)

About Install AIETools part, I am doing the Option B. I will change to the option A. 

![image](https://github.com/user-attachments/assets/3bf7ac9d-d175-4b61-b9a6-aa6b7fb3b72b)

Can you tell me which example can work on Strix successfully?  Thanks!

**Comment by ngdymx** [comment]
Hi @jgmelber, 

I am attempting to download Vitis™ AIE Essentials from the [Ryzen AI Software 1.3 Early Access] site, but I am prompted to obtain approval through the Ryzen AI Software Early Access Secure Site Request.

I submitted this request previously but have not yet received a response. Could you suggest a way to proceed?

Thank you for your assistance.

**Comment by jgmelber** [comment]
You should have access to the EA site now.

**Comment by ngdymx** [comment]
Hi @jgmelber,

The ```passthrough_kernel```  works now. Thanks!
We hope more examples can be available soon.

**Comment by jgmelber** [comment]
`vector_scalar_mul` and some `vision` examples work as well. You can try to port or develop other designs yourself before they land in the repo. Please keep an eye on #1986.
