### ISSUE TITLE
Issue with XDNA™ Driver Installation: GitLab URL Missing and Black Screen on Step 5

### ISSUE THREAD

**Issue by thhongee** [Xilinx/mlir-aie#2003]
Hello, I encountered an issue while installing from https://github.com/Xilinx/mlir-aie. In Step 4 of "Install the XDNA™ Driver(./build.sh -package)," it couldn't find the corresponding file in the GitLab URL (the file has been deleted). So, I went to xdna/tools/info.json and changed the URL to an older version of the GitLab link. However, when I continued to Step 5, "Install XDNA™," the computer would black screen. Even after rebooting, the issue persisted. I had to disable IPU in order to boot (Advanced → CPU Configuration → IPU). Could you please fix this issue? Thank you.

My computer is Ubuntu 24.10 install with Linux 6.11 kernel.

**Comment by jgmelber** [comment]
Please submit this issue to the xdna-driver or XRT repo. In general the Gitlab links for firmware files must match the source code you are building and should not be edited. If the commit hash we suggest doesn't have a valid gitlab link, please try a more recent commit and reopen this issue.
