### ISSUE TITLE
aie-opt stuck

### ISSUE THREAD

**Issue by arkhodamoradi** [Xilinx/mlir-aie#292]
aie-opt and aiecc.py are stuck when processing [this example](https://github.com/singagan/mlir-aie/blob/hdiff/reference_designs/horizontal_diffusion/HDIFF_tri_AIE_objectFIFO_scaled/aie.mlir) after merge [291](https://github.com/Xilinx/mlir-aie/pull/291)

**Comment by AndraBisca** [comment]
Fixed with #296.
