### ISSUE TITLE
mlir_aie_initialize_locks() is empty

### ISSUE THREAD

**Issue by AndraBisca** [Xilinx/mlir-aie#315]
After compiling with aiecc, the function body of mlir_aie_initialize_locks() in the acdc_project/aie_inc.cpp is empty.

**Comment by fifield** [comment]
Isn't that OK if no locks are used? Is there some other context for this bug?

**Comment by AndraBisca** [comment]
I tried this out on tutorial-3 which uses locks and it's still empty.

**Comment by stephenneuendorffer** [comment]
See test/Targets/AIEGenerateXAIE/test_lock_init.mlir

Currently we assume that locks are initialized to zero by default and only generate code here if an initial value is explicitly set.
