### ISSUE TITLE
Some AIE Dialect verifiers call "assert" to check correctness... should return failure() to enable graceful shutdown. 

### ISSUE THREAD

**Issue by SamuelBayliss** [Xilinx/mlir-aie#396]
Code like AIEDialect.cpp 

xilinx::AIE::CoreOp::verify()

**Comment by AndraBisca** [comment]
Fix proposed in PR #397.

There are other Transforms in mlir-aie which also rely on the usage of assert but the change to a more graceful failure is less obvious so I will leave that for future PRs/issues. I am at least currently working on refactoring the ObjectFifo related passes to correct this. Other passes are:
- AIECreatePacketFlows.cpp
- AIECreatePathfindFlows.cpp
- AIEPathfinder.cpp
