### ISSUE TITLE
aiecc.py calls 'llvm-link' from path - opaque-pointer regression means it needs to be sure to call specific LLVM version

### ISSUE THREAD

**Issue by SamuelBayliss** [Xilinx/mlir-aie#423]
As noted in issue #380 - changes to upstream LLVM have required us to stop advancing our LLVM version. This means a specific version of LLVM is required by aiecc.py to produce IR code to feed into the single-core compiler. 

Should we make a call that aiecc.py reference that specific version ( whose location is specified at Build time) rather than rely on what is resolved from the head of PATH when aiecc.py is called?

**Comment by stephenneuendorffer** [comment]
Fixed by #794
