### ISSUE TITLE
runtime_lib build/install depends on Vitis install

### ISSUE THREAD

**Issue by fifield** [Xilinx/mlir-aie#470]
The build and install of `runtime_lib/test_lib` is conditional on `VITIS_ROOT` being defined, but Vitis is not an actual build dependency. As far as I can tell the only requirement to build `test_lib` is LibXAIE which _might_ come from Vitis, but shouldn't need to (see https://github.com/Xilinx/mlir-aie/issues/290)

**Comment by denolf** [comment]
fixed in #496
