### ISSUE TITLE
Where should $VitisSysroot point to?

### ISSUE THREAD

**Issue by hanchenye** [Xilinx/mlir-aie#5]
I assume it is `$mypath/Xilinx/Vitis/2020.1`, but it seems this is not the case?

**Comment by denolf** [comment]
It should point to the sysroot created when running the platform build steps explained in https://xilinx.github.io/mlir-aie/Platform.html.

We will make that clearer in the documentation

**Comment by denolf** [comment]
Updated doc, closing issue.

**Comment by hanchenye** [comment]
@denolf Thanks Kristof!
