### ISSUE TITLE
Remove A/B attribute from `dmaBdOp`

### ISSUE THREAD

**Issue by andrej** [Xilinx/mlir-aie#561]
Currently, our `dmaBdOp` looks like this:

```
AIE.dmaBd(<%buf14 : memref<128xi32>, 0, 128>, 0, [<16, 8>, <1, 2>, <2, 8>])
          ^                                ^  ^ 
         (2)                              (2)(1)
```

`(1)` is the A/B mode attribute, which we don't use.

In today's meeting we have decided to drop that attribute, which will necessitate adjusting several tests and MLIR code that contains this attribute.

Once `(1)` is removed, the brackets `(2)` around the buffer information will become obsolete. Those should be removed as well.

**Comment by stephenneuendorffer** [comment]
I'd like to see a more holistic design of the syntax for this op, rather than a bunch of small incremental changes.
