### ISSUE TITLE
Support vector.transfer_read of scalar memref

### ISSUE THREAD

**Issue by jamestcl-amd** [Xilinx/mlir-aie#584]
- For vector canonicalization, it doesn't support vector.transfer_read from scalar memref
- Sample test at https://github.com/Xilinx/mlir-aie/blob/main/test/dialect/AIEVec/precanonicalization.mlir
- Sample code at https://github.com/Xilinx/mlir-aie/blob/1cf052849d09f0583564dca1b138b165eff9a7d1/lib/Dialect/AIEVec/Transforms/VectorToVectorConversions.cpp#L128
- Workaround:
![image](https://github.com/Xilinx/mlir-aie/assets/142062293/0631c3c8-1ea4-4dc5-9934-89ec2baa64cf)

**Comment by jsetoain** [comment]
@jamestcl-amd 

[PR#586](https://github.com/Xilinx/mlir-aie/pull/586) Deals with this issue. I tried to add you as a reviewer but looks like I'm not allowed. You should be able to review anyway.

**Comment by jamestcl-amd** [comment]
Thanks. I will need Steve to give me permissions against this repo.

**Comment by jsetoain** [comment]
Resolved by #586
