### ISSUE TITLE
Packet switch routing "drop header" feature needs to be configurable

### ISSUE THREAD

**Issue by stephenneuendorffer** [Xilinx/mlir-aie#667]
In the stream switches, when using packet routing, it's possible to drop a packet header in the process of routing.  This needs to be available for configuration in MLIR.

**Comment by erwei-xilinx** [comment]
Yes there is now a flag to force keeping packet headers in the packet routing: https://github.com/Xilinx/mlir-aie/blob/3fe300ad4792b3650d53c079dafd0cc98d602566/lib/Dialect/AIE/Transforms/AIECreatePacketFlows.cpp#L341
