### ISSUE TITLE
'AIE.objectFifo' op expects parent op 'AIE.device' on tutorial-4

### ISSUE THREAD

**Issue by gabrielrodcanal** [Xilinx/mlir-aie#698]
I get this error at the MLIR level when running `make` on tutorial-4. This also happens on the objectFifo version of tutorial-3.

**Comment by gabrielrodcanal** [comment]
The fix is as simple as surrounding all the MLIR code with:
```
AIE.device(xcvc1902) {
// Code
}
```

All the tutorials that make use of `AIE.objectFifo` suffer from this problem.

**Comment by AndraBisca** [comment]
Hey Gabriel! Thanks for pointing this out. I will prepare a patch to fix this issue in all tutorials. In the meantime, please use the fix that you proposed. Apologies for the inconvenience.

**Comment by gabrielrodcanal** [comment]
> Hey Gabriel! Thanks for pointing this out. I will prepare a patch to fix this issue in all tutorials. In the meantime, please use the fix that you proposed. Apologies for the inconvenience.

I'm happy to contribute a pull request with that fix if you haven't fixed that already yourself yet :)
