### ISSUE TITLE
Tutorial 5 fails to compile

### ISSUE THREAD

**Issue by gabrielrodcanal** [Xilinx/mlir-aie#720]
Hi there,
I've noticed that tutorial 5 doesn't compile for me. It's throwing the following errors:
![image](https://github.com/Xilinx/mlir-aie/assets/23747903/77fbb187-e0ee-4eb0-ac92-29d6084fa269)

I'm not sure if it has to do with my local installation or there is some problem with the lowering. Could anyone confirm if this happens to them too?

Note: #698 fixed the issue of missing the `device` when using `objectFifo`. This is an entirely different problem.

**Comment by AndraBisca** [comment]
Hello Gabriel! This is not an issue that has to do with your build, rather this test uses a deprecated API for the problematic functions. You can see an example of the new API [here](https://github.com/Xilinx/mlir-aie/blob/main/test/unit_tests/aie/17_shim_dma_with_core/test.cpp#L114).

**Comment by gabrielrodcanal** [comment]
Hi Andra,
I applied those changes to the `test.cpp` code and I got it to compile. However, when I run the simulation with `make -C aie.mlir.prj/sim` I get the following error:
