### ISSUE TITLE
Dependencies missing in make builds

### ISSUE THREAD

**Issue by LorenzoSun-V** [Xilinx/mlir-aie#74]
When I built AIE tools on x86, I met a fatal error " 'aie/Dialect/ADF/ADFDialect.cpp.inc' file not found."  as the following  picture.
![image](https://user-images.githubusercontent.com/42413198/149080074-3b215e33-1e8e-45e2-a60e-d445edefd80f.png)
Then I checked my build folder, and I do miss the file. So I delete the code in the cpp file and built successfully. Does deleting the "#include" code affect the following test results?

**Comment by stephenneuendorffer** [comment]
Hi..  the .inc files are automatically generated by the build.  This is usually an indicator of an incorrect build setup that is missing some dependencies, or perhaps a bug in an older version of cmake.  you should be able to work around it by running 'make -k 0'.  Generally, we use ninja which is more predictable about dependencies on generated files.  What version of cmake are you using?

**Comment by Gakkkkkki** [comment]
Thanks for your reply.
According to your /docs/Building.md, I installed cmake 3.17.5, ninja 1.8.2, Xilinx Vitis 2020.2(differ from 2020.1 in your doc) and jobilb.
![image](https://user-images.githubusercontent.com/42413198/149084441-9250d6d6-4cf7-458e-9046-de07418d2acd.png)
![image](https://user-images.githubusercontent.com/42413198/149084497-4a28643f-84a6-43cd-97db-be039c0a8716.png)

First of all, I git clone the llvm-project and then git checkout commithash(provided in /utils/clone-llvm.sh) like this.
![image](https://user-images.githubusercontent.com/42413198/149085755-7c431fc3-7b9f-4057-96df-6ad3b78d9d5a.png)

Next, I cmake using the following instruction(provided in /utils/build-llvm.sh) in the created build folder but I met an error like this:
![image](https://user-images.githubusercontent.com/42413198/149088352-5587ad66-336e-4e38-bd8a-fc93cccd6af2.png)
![image](https://user-images.githubusercontent.com/42413198/149088527-80de63ac-8c7c-45fb-96f4-529371926859.png)
So I delete the LLD button like this:
![image](https://user-images.githubusercontent.com/42413198/149088835-1ee19d1b-eb92-4b24-bca6-46e15937c486.png).
After I cmake sucessfully, I use ![image](https://user-images.githubusercontent.com/42413198/149089381-e523cbbf-7215-46c2-a714-6ddeb8e66215.png) and compile LLVM successfully.

To build AIE tools, 
![image](https://user-images.githubusercontent.com/42413198/149090609-109ad167-a817-4e7f-86f4-fe7fdb608de4.png) were both git. Then I cmake using the following instruction(provided in /.github/workflows/buildAndTest.yml) in the create build folder in mlir-aie project:
![image](https://user-images.githubusercontent.com/42413198/149091384-3e9611b2-0e79-4f31-ad1f-f493c26d222e.png)
![image](https://user-images.githubusercontent.com/42413198/149091648-15cfe6e3-b4c6-4e77-8023-5d404d0ed5ac.png)
Then I met the fatal error:
![image](https://user-images.githubusercontent.com/42413198/149091781-f9010fbc-0329-4012-8983-cbf226d49f92.png)

I had post what I did after meeting the error in this issue.  This does confuse me for a whole while.
Look forward to receiving your reply ASAP!  :-)

**Comment by stephenneuendorffer** [comment]
It looks like you're still using make to compile.  To use ninja, run "cmake -GNinja ...." and use ninja to build.
