### ISSUE TITLE
Support for Linux on RyzenAI desktop and laptops

### ISSUE THREAD

**Issue by chaudhariatul** [Xilinx/mlir-aie#778]
Thanks for documentation and tutorials for RyzenAI on Windows and using WSL.

Is there any documentation for Desktops or Laptops when Linux booted?
Need more details on how to enable and verify the AI Engine when Linux booted.

**Comment by jgmelber** [comment]
Linux drivers are not currently available. We will pass the request and interest on to the driver developers.

**Comment by chaudhariatul** [comment]
Hope this issue on RyzenAI helps with a boost on this request:

https://github.com/amd/RyzenAI-SW/issues/2

**Comment by stalkerg** [comment]
It requires a specific llvm version and can't be integrated into the system llvm (from Linux distribution). Seems like they are trying to bundle the most complex part in `Versal`, but it will not work for end-users the same as ROCm (at least for Linux desktop users)
We need the Mesa-level solution to start making Desktop applications for end-users (not for businesses OR scientists). 

Anyway, firstly, we should get drivers and docs for Ryzen AI after that, we can try to build our own stack or improve the current one. 
PS Seems like Tenstorrent has a simular arch.

**Comment by chaudhariatul** [comment]
Support for linux OS where we are able to build business/research applications running on edge devices will be a big incentive to adopt RyzenAI based small form factor devices.

**Comment by tetrahedronix** [comment]
+1

**Comment by jgmelber** [comment]
Closed in #971
