### ISSUE TITLE
Documentation has been removed

### ISSUE THREAD

**Issue by gabrielrodcanal** [Xilinx/mlir-aie#948]
Hi,
The documentation for the dialects was removed a while ago. I'd like to ask if this was intentional and if not can it be restored? If you check https://github.com/Xilinx/mlir-aie/tree/main/docs you'll see that all the links to "Generated code documentation" are broken.

**Comment by abisca** [comment]
Related to #926.

**Comment by makslevental** [comment]
Have no clue how those links ever worked but all of those markdown files are on the `gh-pages` branch not the `main` branch: https://github.com/Xilinx/mlir-aie/tree/gh-pages.

**Comment by makslevental** [comment]
Docs are fixed https://xilinx.github.io/mlir-aie/AIE.html
